In [35]:
import numpy as np
import pandas as pd
import missingno as msno
import matplotlib.pyplot as plt
import warnings

plt.style.use('seaborn-paper')
plt.rc('text', usetex=True)
plt.rc('font', family='sans-serif')
plt.rc('font', size=18)
plt.rc('axes', titlesize=16)
plt.rc('axes', labelsize=16)
plt.rc('xtick', labelsize=14)
plt.rc('ytick', labelsize=14)
plt.rc('legend', fontsize=14)
plt.rc('lines', markersize=16)
plt.rc('axes', grid=False)
warnings.filterwarnings('ignore')

In [36]:
df = pd.read_csv('sp500_data.csv')

In [37]:
df.head()

,Date,MMM,AOS,ABT,ABBV,ACN,ATVI,ADM,ADBE,ADP,...,WTW,GWW,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZION,ZTS
0,2002-01-02 00:00:00-05:00,32.203045,2.212114,15.091696,NaN,18.958561,2.896660,8.765644,15.845818,28.816738,...,38.845188,32.919434,NaN,11.956753,NaN,6.078373,24.813334,26.646757,35.213402,NaN
1,2002-01-03 00:00:00-05:00,32.095810,2.265250,15.105213,NaN,18.365429,2.888986,8.672853,16.462931,28.802010,...,39.341091,33.663055,NaN,12.011857,NaN,6.206298,25.435556,26.479279,35.793713,NaN
2,2002-01-04 00:00:00-05:00,32.192039,2.342646,15.078183,NaN,20.036322,2.941612,8.351178,17.866356,28.752844,...,39.258427,33.862743,NaN,11.918609,NaN,6.446953,26.133333,26.047350,36.094112,NaN
3,2002-01-07 00:00:00-05:00,31.807161,2.329939,14.972778,NaN,19.132162,2.854997,8.307877,17.995756,28.138477,...,38.266640,33.759449,NaN,12.003378,NaN,6.567276,25.680000,26.047350,36.073627,NaN
4,2002-01-08 00:00:00-05:00,31.628462,2.229442,14.875486,NaN,19.732533,2.850611,8.493462,18.234632,28.113905,...,35.869812,33.773212,NaN,11.876226,NaN,6.693936,25.799999,26.884760,36.012177,NaN

In [38]:
# Drop columns if they have any missing values
df = df.dropna(axis=1)

In [39]:
df.head()

,Date,MMM,AOS,ABT,ACN,ATVI,ADM,ADBE,ADP,AES,...,WY,WHR,WMB,WTW,GWW,XEL,YUM,ZBRA,ZBH,ZION
0,2002-01-02 00:00:00-05:00,32.203045,2.212114,15.091696,18.958561,2.896660,8.765644,15.845818,28.816738,12.116564,...,9.542104,40.434368,9.210050,38.845188,32.919434,11.956753,6.078373,24.813334,26.646757,35.213402
1,2002-01-03 00:00:00-05:00,32.095810,2.265250,15.105213,18.365429,2.888986,8.672853,16.462931,28.802010,11.907282,...,9.600784,40.634033,9.078835,39.341091,33.663055,12.011857,6.206298,25.435556,26.479279,35.793713
2,2002-01-04 00:00:00-05:00,32.192039,2.342646,15.078183,20.036322,2.941612,8.351178,17.866356,28.752844,12.592856,...,9.872858,41.194229,8.837678,39.258427,33.862743,11.918609,6.446953,26.133333,26.047350,36.094112
3,2002-01-07 00:00:00-05:00,31.807161,2.329939,14.972778,19.132162,2.854997,8.307877,17.995756,28.138477,12.874298,...,9.842628,40.878082,8.866047,38.266640,33.759449,12.003378,6.567276,25.680000,26.047350,36.073627
4,2002-01-08 00:00:00-05:00,31.628462,2.229442,14.875486,19.732533,2.850611,8.493462,18.234632,28.113905,12.823786,...,9.654137,40.218033,9.032732,35.869812,33.773212,11.876226,6.693936,25.799999,26.884760,36.012177

In [40]:
def calculate_returns(price_data):
    # Calculate daily returns as percentage change
    return price_data.pct_change().dropna()

def calculate_correlations(returns_data):
    # Calculate the correlation matrix for the returns
    return returns_data.corr()

In [41]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')

In [42]:
df

,MMM,AOS,ABT,ACN,ATVI,ADM,ADBE,ADP,AES,AFL,...,WY,WHR,WMB,WTW,GWW,XEL,YUM,ZBRA,ZBH,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2002-01-02 00:00:00-05:00,32.203045,2.212114,15.091696,18.958561,2.896660,8.765644,15.845818,28.816738,12.116564,7.536060,...,9.542104,40.434368,9.210050,38.845188,32.919434,11.956753,6.078373,24.813334,26.646757,35.213402
2002-01-03 00:00:00-05:00,32.095810,2.265250,15.105213,18.365429,2.888986,8.672853,16.462931,28.802010,11.907282,7.453666,...,9.600784,40.634033,9.078835,39.341091,33.663055,12.011857,6.206298,25.435556,26.479279,35.793713
2002-01-04 00:00:00-05:00,32.192039,2.342646,15.078183,20.036322,2.941612,8.351178,17.866356,28.752844,12.592856,7.580428,...,9.872858,41.194229,8.837678,39.258427,33.862743,11.918609,6.446953,26.133333,26.047350,36.094112
2002-01-07 00:00:00-05:00,31.807161,2.329939,14.972778,19.132162,2.854997,8.307877,17.995756,28.138477,12.874298,7.326900,...,9.842628,40.878082,8.866047,38.266640,33.759449,12.003378,6.567276,25.680000,26.047350,36.073627
2002-01-08 00:00:00-05:00,31.628462,2.229442,14.875486,19.732533,2.850611,8.493462,18.234632,28.113905,12.823786,8.093815,...,9.654137,40.218033,9.032732,35.869812,33.773212,11.876226,6.693936,25.799999,26.884760,36.012177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23 00:00:00-05:00,115.073792,56.136066,106.645424,263.014862,75.139404,93.052528,338.450012,238.199707,28.082802,70.472534,...,30.101589,136.164230,32.356754,241.797043,560.591492,69.309738,127.117897,248.220001,126.238785,46.701611
2022-12-27 00:00:00-05:00,115.150421,56.895725,107.029884,262.243896,74.981117,94.321159,335.089996,238.288681,28.219885,70.953812,...,30.082472,136.231537,32.444149,241.985046,560.819702,69.935120,128.104065,251.000000,126.826675,47.077538
2022-12-28 00:00:00-05:00,113.301804,56.007812,106.300385,260.079193,75.238342,92.069099,328.329987,235.144852,27.730295,70.197517,...,29.279507,133.020203,31.774101,239.175171,552.615662,69.431381,127.522232,246.839996,125.541275,46.238934
2022-12-29 00:00:00-05:00,115.485664,56.885860,108.745193,265.278412,75.940765,91.577377,337.579987,237.883331,28.210093,70.796654,...,29.939083,137.587219,32.016872,243.463882,557.734436,69.923317,128.192825,257.529999,127.374718,47.308876
2022-12-30 00:00:00-05:00,114.863068,56.471497,108.232574,263.756195,75.733009,91.311852,336.529999,236.143356,28.161135,70.659157,...,29.633194,136.010406,31.948896,242.808685,551.812073,68.978806,126.309235,256.410004,127.045898,47.385986

In [43]:
# Return and correlation calculations
returns = calculate_returns(df)
correlations = calculate_correlations(returns)

In [47]:
returns

,MMM,AOS,ABT,ACN,ATVI,ADM,ADBE,ADP,AES,AFL,...,WY,WHR,WMB,WTW,GWW,XEL,YUM,ZBRA,ZBH,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2002-01-03 00:00:00-05:00,-0.003330,0.024021,0.000896,-0.031286,-0.002649,-0.010586,0.038945,-0.000511,-0.017272,-0.010933,...,0.006150,0.004938,-0.014247,0.012766,0.022589,0.004609,0.021046,0.025076,-0.006285,0.016480
2002-01-04 00:00:00-05:00,0.002998,0.034167,-0.001789,0.090980,0.018216,-0.037090,0.085248,-0.001707,0.057576,0.017007,...,0.028339,0.013786,-0.026563,-0.002101,0.005932,-0.007763,0.038776,0.027433,-0.016312,0.008393
2002-01-07 00:00:00-05:00,-0.011956,-0.005424,-0.006991,-0.045126,-0.029445,-0.005185,0.007243,-0.021367,0.022349,-0.033445,...,-0.003062,-0.007675,0.003210,-0.025263,-0.003050,0.007112,0.018663,-0.017347,0.000000,-0.000568
2002-01-08 00:00:00-05:00,-0.005618,-0.043133,-0.006498,0.031380,-0.001536,0.022338,0.013274,-0.000873,-0.003924,0.104671,...,-0.019150,-0.016147,0.018800,-0.062635,0.000408,-0.010593,0.019287,0.004673,0.032150,-0.001703
2002-01-09 00:00:00-05:00,-0.003476,0.002590,-0.005450,0.010630,-0.017308,0.002913,0.027020,-0.009266,-0.026449,0.029757,...,-0.002579,-0.008274,0.005104,0.025807,0.007951,-0.003212,0.000946,-0.044617,0.006557,-0.004550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23 00:00:00-05:00,-0.011925,0.011915,0.001389,0.005023,0.003302,0.012087,0.005735,0.007443,0.013070,0.011846,...,0.014171,0.014543,0.023027,0.008626,0.006644,0.012852,0.000621,0.002869,0.001106,0.003521
2022-12-27 00:00:00-05:00,0.000666,0.013532,0.003605,-0.002931,-0.002107,0.013633,-0.009928,0.000374,0.004881,0.006829,...,-0.000635,0.000494,0.002701,0.000778,0.000407,0.009023,0.007758,0.011200,0.004657,0.008050
2022-12-28 00:00:00-05:00,-0.016054,-0.015606,-0.006816,-0.008255,0.003431,-0.023877,-0.020174,-0.013193,-0.017349,-0.010659,...,-0.026692,-0.023573,-0.020652,-0.011612,-0.014629,-0.007203,-0.004542,-0.016574,-0.010135,-0.017813
2022-12-29 00:00:00-05:00,0.019275,0.015677,0.022999,0.019991,0.009336,-0.005341,0.028173,0.011646,0.017302,0.008535,...,0.022527,0.034333,0.007641,0.017931,0.009263,0.007085,0.005259,0.043307,0.014604,0.023139
2022-12-30 00:00:00-05:00,-0.005391,-0.007284,-0.004714,-0.005738,-0.002736,-0.002899,-0.003110,-0.007314,-0.001735,-0.001942,...,-0.010217,-0.011460,-0.002123,-0.002691,-0.010619,-0.013508,-0.014693,-0.004349,-0.002582,0.001630

In [48]:
correlations

,MMM,AOS,ABT,ACN,ATVI,ADM,ADBE,ADP,AES,AFL,...,WY,WHR,WMB,WTW,GWW,XEL,YUM,ZBRA,ZBH,ZION
MMM,1.000000,0.493377,0.423772,0.442374,0.306802,0.434837,0.427115,0.539188,0.317380,0.503776,...,0.563270,0.515525,0.314569,0.400854,0.538969,0.310875,0.460969,0.429374,0.415121,0.453452
AOS,0.493377,1.000000,0.317945,0.363222,0.294964,0.359957,0.389470,0.429930,0.299088,0.428564,...,0.493071,0.460194,0.273848,0.358093,0.469854,0.236810,0.382643,0.414810,0.331375,0.405520
ABT,0.423772,0.317945,1.000000,0.378923,0.279701,0.314567,0.369943,0.450003,0.234043,0.326963,...,0.378098,0.343951,0.224757,0.345021,0.379955,0.324371,0.354250,0.333749,0.413591,0.266317
ACN,0.442374,0.363222,0.378923,1.000000,0.327283,0.344831,0.439491,0.525028,0.324920,0.389296,...,0.449520,0.387578,0.310874,0.383899,0.424450,0.277567,0.351687,0.406132,0.361696,0.326898
ATVI,0.306802,0.294964,0.279701,0.327283,1.000000,0.270551,0.420034,0.343116,0.244423,0.280614,...,0.304505,0.267648,0.238685,0.229126,0.293441,0.221600,0.252229,0.296234,0.223264,0.198249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XEL,0.310875,0.236810,0.324371,0.277567,0.221600,0.287899,0.272484,0.347833,0.324851,0.309356,...,0.335064,0.272976,0.176078,0.236268,0.304930,1.000000,0.273452,0.217250,0.228109,0.184783
YUM,0.460969,0.382643,0.354250,0.351687,0.252229,0.338308,0.371359,0.433110,0.277222,0.433983,...,0.475319,0.426097,0.244198,0.356761,0.403714,0.273452,1.000000,0.359386,0.374886,0.367457
ZBRA,0.429374,0.414810,0.333749,0.406132,0.296234,0.339783,0.425343,0.420767,0.310648,0.360218,...,0.448675,0.407026,0.300300,0.340732,0.375690,0.217250,0.359386,1.000000,0.334930,0.334919
ZBH,0.415121,0.331375,0.413591,0.361696,0.223264,0.324965,0.333741,0.398015,0.274255,0.398042,...,0.435449,0.373130,0.261704,0.358446,0.353168,0.228109,0.374886,0.334930,1.000000,0.349107
ZION,0.453452,0.405520,0.266317,0.326898,0.198249,0.352396,0.311984,0.387519,0.284876,0.580669,...,0.485848,0.461814,0.273571,0.356326,0.398357,0.184783,0.367457,0.334919,0.349107,1.000000

In [46]:
# Save to CSV
returns.to_csv('returns.csv')
correlations.to_csv('correlations.csv')